name: rest-docs-api-spec Fork Build

on:
  push:
    branches:
      - publish-fork

jobs:
  ci-build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build & Test
        run: ./gradlew clean build coveralls